export default{
  //个人中心
  logIn:'/v1/seller/doLogin',//商家登录
  logOut:'/v1/seller/logout',//商家退出登录
  updateWindowPic:'/v1/seller/updateWindowPic',//修改窗口头像
  getWinPicUrl:'/v1/seller/upload', //获取图片地址
  getUserMsg:'/v1/seller/get',//获取商家信息
  getDeliveryMsg:'/v1/delivery/get',//获取配送设置信息
  editWinName:'/v1/seller/updateWindowName',//修改窗口名
  editOrderPhone:'/v1/seller/setOrderPhone',//修改订餐电话
  updateBusinessState:'/v1/seller/updateBusinessState',//修改营业状态
  addChuangKouPic:'/v1/sellerPic/insert',//添加窗口图片
  addZiZhiPic:'/v1/sellerPaper/insert',//添加资质图片
  addYuanGongPic:'/v1/sellerEmp/insert',//添加员工图片
  getChuangKou:'/v1/sellerPic/query',//获取窗口图片列表
  getZiZhi:'/v1/sellerPaper/query',//获取资质图片列表
  getYuanGong:'/v1/sellerEmp/query',//获取员工图片列表
  delChuangKou:'/v1/sellerPic/query',//删除窗口图片
  delZiZhi:'/v1/sellerPaper/query',//删除资质图片
  delYuanGong:'/v1/sellerEmp/query',//删除员工图片 
  editBeginFee:'/v1/delivery/setDeliveryMinAmount',//修改起送费
  editBusiTime:'/v1/seller/updateBusinessTime',//修改营业时间
  editAcceptTime:'/v1/seller/updateOrderTime',//修改接单时间和是否自动接单
  sendModelSet:'/v1/delivery/setDeliveryMode',//配送方式设置
  mealTimeSet:'/v1/delivery/setMealTime',//设置出餐时间
  saveFeedBack:'/v1/seller/feedback',//提交反馈意见
  editAutoPrint:'/v1/seller/updateAutoPrintState',//修改自动打印状态
  //商品管理
  getGoodsKinds:'/v1/goodsKind/query',//查找商品分类
  getGoodsList:'/v1/goods/query',//查找商品
  editGoodsType:'/v1/goodsKind/update',//修改商品类别
  delGoodsType:'/v1/goodsKind/batchDelete',//商品分类删除
  addGoodsType:'/v1/goodsKind/insert',//商品分类添加
  goodsDown:'/v1/goods/down',//商品下架
  goodsUp:'/v1/goods/up',//商品上架
  goodsEdit:'/v1/goods/update',//商品编辑
  getGoodsPicUrl:'/v1/goods/upload',//获取商品图片地址
  goodsAdd:'/v1/goods/insert',//商品添加
  goodsSort:'/v1/goods/sort',//商品排序 
  goodsDel:'/v1/goods/batchDelete',//商品删除
  //门店运营
  getSellerIncomeByDay:'/v1/order/getSellerIncomeByDay',//获取商家今日营业订单数据
  //评价
  getCommentsAll:'/v1/order/getSellerAllComment',//获取商家全部评价
  getSellerScore:'/v1/order/getSellerScore',//获取商家评分
  getSellerGoodsComments:'/v1/order/getGoodsComment',//获取商家商品评价
  //订单
  getFinishOrders:'/v1/order/queryFinish',//获取已完成订单
  getOrderMsg:'/v1/order/getOrder',//获取订单详细信息
  getSellerOrdersMonth:'/v1/order/getSellerIncomeByMonth',//商家订单按月汇总
  //公告信息
  addNotice:'/v1/sellerNotice/insert',//创建公告
  getNotice:'/v1/sellerNotice/query',//获取公告信息
  publishNotice:'/v1/sellerNotice/publish',//发布公告
  //订单管理
  getOrderGoing:'/v1/order/queryGoing',//获取进行中订单
  getOrderMode:'/v1/order/getOrderMode',//获取订单配送信息
  getOrderState:'/v1/order/queryOrderState',//获取订单状态列表
  urgeOrder:'/v1/order/remind',//催单
  diningOut:'/v1/order/diningOut',//出餐完毕
  cancelOrder:'/v1/order/cancel',//取消订单
  getOrderFinish:'/v1/order/queryFinish',//获取已完成订单
  getOrderCancel:'/v1/order/queryCancel',//获取已取消订单
  getOrderRemind:'/v1/order/queryRemind',//获取催单订单
  getOrderNew:'/v1/order/query',//获取新订单
  orderAccept:'/v1/order/accept',//确认接单
}